services:
  django:
    container_name: django
    image: django:1
    build: ./srcs/django/
    volumes:
      - django_volume:/project
      - frontend_volume:/var/www/html
    env_file:
      - .env
    networks:
      - transcendence

  nginx:
    container_name: nginx
    image: nginx:1
    build: ./srcs/nginx/
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - frontend_volume:/var/www/html
    env_file:
      - .env
    depends_on:
      - django
    networks:
      - transcendence

  frontend:
    container_name: frontend
    image: frontend:1
    build: ./srcs/frontend/
    networks:
      - transcendence
    volumes:
      - frontend_volume:/var/www/html
    depends_on:
      - django

volumes:
  django_volume:
    name: django_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole42/data/django_volume
      o : bind

  frontend_volume:
    name: frontend_volume
    driver: local
    driver_opts:
      type : none
      device: /home/user/ecole42/data/frontend_volume
      o : bind

networks:
  transcendence:
    driver: bridge
